name: 'Configure Xcode'
description: 'Set up Xcode version'
runs:
  using: composite
  steps:
    - name: Set up Xcode
      shell: bash
      run: |
        sudo xcode-select -s /Applications/Xcode_27.0.0.app
