name: XToolMac
options:
  bundleIdPrefix: sh.xtool
packages:
  xtool:
    path: ..
    group: ""
fileGroups:
  - Support
targets:
  XToolMac:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: XToolMac
      - path: Resources/xtool
        buildPhase:
          copyFiles:
            destination: resources
            subpath: bin
    configFiles:
      Debug: Support/Debug.xcconfig
      Release: Support/Release.xcconfig
    dependencies:
      - package: xtool
        product: XToolSupport
